language: generic
services:
  - docker

notifications:
  email:
    on_success: never
    on_failure: never

env:
  global:
    - NOT_TEST_BUILD=true
    
matrix:
  include:
    - env: ROS_DISTRO=kinetic DOCKER_IMAGE=rosindustrial/noether:kinetic
    - env: ROS_DISTRO=melodic DOCKER_IMAGE=rosindustrial/noether:melodic
    - env: ROS_DISTRO=noetic DOCKER_IMAGE=rosindustrial/noether:noetic
    
install:
  - git clone --quiet --depth 1 https://github.com/ros-industrial/industrial_ci.git .industrial_ci -b master
script:
  - .industrial_ci/travis.sh
